In [30]:
n = 2
commands = ["RIGHT", "DOWN"]
n = 3
commands = ["DOWN", "RIGHT", "UP"]
n = 2
commands = ["UP", "UP", "UP", "UP", "UP"]
n = 3
commands = [
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
]
n = 3
commands = [
    "RIGHT",
    "RIGHT",
    "RIGHT",
    "RIGHT",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
]
n = 2
commands = [
    "RIGHT",
    "RIGHT",
    "RIGHT",
    "RIGHT",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
    "DOWN",
]
n = 2
commands = ["RIGHT", "DOWN", "RIGHT", "DOWN"]
n = 3
commands = ["RIGHT", "DOWN", "RIGHT", "DOWN"]

In [31]:
import numpy as np

square = np.arange(0, n**2).reshape(n, n)
print(square)
start = [0, 0]
for c in commands:
    if c == "RIGHT":
        start[1] += 1
    elif c == "DOWN":
        start[0] += 1
    elif c == "UP":
        start[0] -= 1
    elif c == "LEFT":
        start[1] -= 1

# Handle box edges
if start[0] < 0:
    start[0] = 0
if start[1] < 0:
    start[1] = 0
if start[0] > n - 1:
    start[0] = n - 1
if start[1] > n - 1:
    start[1] = n - 1

print(square[start[0], start[1]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
